tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: service_type
            field:
              options:
                groupclass: 團課
                onebyone: 一對一
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 'service type'
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: day_of_week
            field:
              options:
                sun: 星期日
                mon: 星期一
                tue: 星期二
                wed: 星期三
                thu: 星期四
                fri: 星期五
                sat: 星期六
                any: 不定期
              taggable: true
              push_tags: true
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 'day of week'
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: subject
            field:
              antlers: false
              type: textarea
              display: subject
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: bard_field
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: true
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: 'Bard Field'
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: teacher
            field:
              options:
                Howard: Howard
                Mao: Mao
              taggable: true
              push_tags: true
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: teacher
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: service_tag
            field:
              placeholder: 'Type and press ↩ Enter'
              type: taggable
              display: 'service tag'
              icon: tags
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
title: Service
