tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: 標題
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              input_type: text
              antlers: false
              hide_display: false
          -
            handle: service_type
            field:
              options:
                redline: 紅繩訓練
                strength: 肌力訓練
                massage: 運動按摩
                reconstructio: 骨科術後功能重建
                correction: 姿勢矯正
                lecture: 企業健康講座
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 服務類別
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: source_type
            field:
              options:
                groupclass: 團課
                onebyone: 一對一
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 上課方式
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: feature_pic
            field:
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 圖片
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: essay
            field:
              antlers: false
              type: textarea
              display: 短文說明
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: bard_field
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              smart_typography: false
              save_html: false
              inline: false
              toolbar_mode: fixed
              reading_time: true
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: 內文
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: teacher
            field:
              options:
                Howard: Howard
                Mao: Mao
              taggable: true
              push_tags: true
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 老師
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: taggable_field
            field:
              placeholder: 'Type and press ↩ Enter'
              type: taggable
              display: 標籤
              icon: tags
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: class_week_date
            field:
              options:
                sun: 星期日
                mon: 星期一
                tue: 星期二
                wed: 星期三
                thu: 星期四
                fri: 星期五
                sat: 星期六
                any: 預約制
              inline: false
              type: checkboxes
              display: 上課時間
              icon: checkboxes
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              instructions_position: above
              listable: true
              visibility: visible
              replicator_preview: true
              from: title
              generate: true
              show_regenerate: false
              hide_display: false
title: Service
